/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiResidents200Item,
  GetApiResidents400,
  PostApiEmbeed200,
  PostApiEmbeed400,
  PostApiEmbeed409,
  PostApiEmbeedBodyOne,
  PostApiEmbeedBodyThree,
  PostApiEmbeedBodyTwo,
  PostApiRecognize200,
  PostApiRecognizeBodyOne,
  PostApiRecognizeBodyThree,
  PostApiRecognizeBodyTwo
} from './model';

import { axiosMutator } from '../../infra/api';




export const getApiResidents = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosMutator<GetApiResidents200Item[]>(
      {url: `/api/residents`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiResidentsQueryKey = () => {
    return [
    `/api/residents`
    ] as const;
    }

    
export const getGetApiResidentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiResidents>>, TError = GetApiResidents400>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiResidents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiResidentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiResidents>>> = ({ signal }) => getApiResidents(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiResidents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiResidentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiResidents>>>
export type GetApiResidentsQueryError = GetApiResidents400


export function useGetApiResidents<TData = Awaited<ReturnType<typeof getApiResidents>>, TError = GetApiResidents400>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiResidents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiResidents>>,
          TError,
          Awaited<ReturnType<typeof getApiResidents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiResidents<TData = Awaited<ReturnType<typeof getApiResidents>>, TError = GetApiResidents400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiResidents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiResidents>>,
          TError,
          Awaited<ReturnType<typeof getApiResidents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiResidents<TData = Awaited<ReturnType<typeof getApiResidents>>, TError = GetApiResidents400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiResidents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiResidents<TData = Awaited<ReturnType<typeof getApiResidents>>, TError = GetApiResidents400>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiResidents>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiResidentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postApiEmbeed = (
    postApiEmbeedBody: PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree,
 signal?: AbortSignal
) => {
      
      
      return axiosMutator<PostApiEmbeed200>(
      {url: `/api/embeed`, method: 'POST',
      data: postApiEmbeedBody, signal
    },
      );
    }
  


export const getPostApiEmbeedMutationOptions = <TError = PostApiEmbeed400 | PostApiEmbeed409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEmbeed>>, TError,{data: PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiEmbeed>>, TError,{data: PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree}, TContext> => {

const mutationKey = ['postApiEmbeed'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEmbeed>>, {data: PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  postApiEmbeed(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiEmbeedMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEmbeed>>>
    export type PostApiEmbeedMutationBody = PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree
    export type PostApiEmbeedMutationError = PostApiEmbeed400 | PostApiEmbeed409

    export const usePostApiEmbeed = <TError = PostApiEmbeed400 | PostApiEmbeed409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEmbeed>>, TError,{data: PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiEmbeed>>,
        TError,
        {data: PostApiEmbeedBodyOne | PostApiEmbeedBodyTwo | PostApiEmbeedBodyThree},
        TContext
      > => {

      const mutationOptions = getPostApiEmbeedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const postApiRecognize = (
    postApiRecognizeBody: PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree,
 signal?: AbortSignal
) => {
      
      
      return axiosMutator<PostApiRecognize200>(
      {url: `/api/recognize`, method: 'POST',
      data: postApiRecognizeBody, signal
    },
      );
    }
  


export const getPostApiRecognizeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRecognize>>, TError,{data: PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiRecognize>>, TError,{data: PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree}, TContext> => {

const mutationKey = ['postApiRecognize'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiRecognize>>, {data: PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree}> = (props) => {
          const {data} = props ?? {};

          return  postApiRecognize(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiRecognizeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiRecognize>>>
    export type PostApiRecognizeMutationBody = PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree
    export type PostApiRecognizeMutationError = unknown

    export const usePostApiRecognize = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiRecognize>>, TError,{data: PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiRecognize>>,
        TError,
        {data: PostApiRecognizeBodyOne | PostApiRecognizeBodyTwo | PostApiRecognizeBodyThree},
        TContext
      > => {

      const mutationOptions = getPostApiRecognizeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
