/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { GetApiConfigByName200Config } from './getApiConfigByName200Config';

export type GetApiConfigByName200 = {
  success: boolean;
  config: GetApiConfigByName200Config;
};
