/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostApiRecognize200Resident } from './postApiRecognize200Resident';

export type PostApiRecognize200 = {
  success: boolean;
  resident?: PostApiRecognize200Resident;
};
