/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PostApiEmbeed200Resident } from './postApiEmbeed200Resident';

export type PostApiEmbeed200 = {
  success: boolean;
  resident: PostApiEmbeed200Resident;
};
