/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutApiConfigBodyThreeValue } from './putApiConfigBodyThreeValue';

export type PutApiConfigBodyThree = {
  name: string;
  value: PutApiConfigBodyThreeValue;
};
