/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutApiConfigBodyTwoValue } from './putApiConfigBodyTwoValue';

export type PutApiConfigBodyTwo = {
  name: string;
  value: PutApiConfigBodyTwoValue;
};
