/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import type { PutApiConfig201Config } from './putApiConfig201Config';

export type PutApiConfig201 = {
  success: boolean;
  config: PutApiConfig201Config;
};
