/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */

export type PutApiConfig201Config = {
  id: string;
  name: string;
  value: string;
  type: string;
  createdAt: string;
  updatedAt: string;
};
